---
- name: Add democratic-csi chart repo
  community.kubernetes.helm_repository:
    name: democratic-csi
    repo_url: "https://democratic-csi.github.io/charts/"
  when: not democratic_csi.check_config_only

- name: "Ensure configuration directory is present"
  ansible.builtin.file:
    path: "/tmp/k8s-config/democratic-csi"
    state: directory
    mode: '0700'

- name: "copy values file"
  ansible.builtin.template:
    src: "values-{{ item.driver }}.yml.j2"
    dest: "/tmp/k8s-config/democratic-csi/values-{{ item.driver }}.yml"
    mode: '0600'
  loop: "{{ democratic_csi.release }}"

- name: Deploy democratic-csi chart using values files on target
  community.kubernetes.helm:
    release_name: "{{ item.name }}"
    chart_ref: democratic-csi/democratic-csi
    release_namespace: "{{ item.namespace | default(democratic_csi_release_namespace) }}"
    chart_version: "{{ democratic_csi_chart_version }}"
    create_namespace: true
    update_repo_cache: true
    wait: true
    wait_timeout: "20m"
    values_files:
      - "/tmp/k8s-config/democratic-csi/values-{{ item.name }}.yml"
    kubeconfig: "{{ kubeconfig }}"
  loop: "{{ democratic_csi.release }}"
  when: not democratic_csi.check_config_only|default(false)

- name: "Remove configuration temporary directory"
  ansible.builtin.file:
    path: "/tmp/k8s-config/democratic-csi"
    state: absent
  when: not democratic_csi.keep_tmpfiles|default(false)
