---
- name: Converge
  hosts: all
  connection: local
  become: true
  vars:
    democratic_csi:
      keep_tmpfiles: true
      config_only: true
      default_api_host: "truenas.example.com"
      default_api_allowInsecure: true
      default_api_key: "astronguniquesecurekey"
      default_ssh_host: "truenas.example.com"
      default_zfs_sudoEnabled: true
      release:
        - name: "truenas-iscsi"
          driver: "freenas-iscsi"
          zfs_datasetParentName: "pool/k8s/v"
          zfs_detachedSnapshotsDatasetParentName: "pool/k8s/s"
          portal: "192.168.1.99:3260"
          portalGroup: "1"
          pnitiatorGroup: "1"
          zvolBlockSize: "64k"
          extentRpm: "5400"
          ssh_privatekey: |
            -----BEGIN RSA PRIVATE KEY-----
            ...
            -----END RSA PRIVATE KEY-----
        - name: "truenas-nfs"
          driver: "freenas-nfs"
          sc_defaultClass: true
          nfs_host: "192.168.1.99"
          nfs_shareAllowedNetworks:
            - "192.168.1.0/24"
            - "192.168.2.0/24"
          ssh_privatekey: |
            -----BEGIN RSA PRIVATE KEY-----
            ...
            -----END RSA PRIVATE KEY-----

  roles:
    - role: "infra_monkey.democratic_csi"
