---
- name: Converge
  hosts: all
  connection: local
  become: true
  vars:
    democratic_csi_keep_tmpfiles: true
    democratic_csi_check_config_only: true
    democratic_csi_protocol:
      - truenas-iscsi
      - truenas-nfs
    democratic_csi_api_host: "truenas.example.com"
    democratic_csi_api_allowInsecure: true
    democratic_csi_api_key: "astronguniquesecurekey"
    democratic_csi_ssh_host: "truenas.example.com"
    democratic_csi_zfs_sudoEnabled: true
    democratic_csi_ssh_privatekey: |
      -----BEGIN RSA PRIVATE KEY-----
      ...
      -----END RSA PRIVATE KEY-----
    democratic_csi_iscsi_zfs_datasetParentName: "pool/k8s/v"
    democratic_csi_iscsi_zfs_detachedSnapshotsDatasetParentName: "pool/k8s/s"
    democratic_csi_iscsi_portal: "192.168.1.99:3260"
    democratic_csi_iscsi_portal_PortalGroup: "1"
    democratic_csi_iscsi_portal_InitiatorGroup: "1"
    democratic_csi_iscsi_zvolBlockSize: "64k"
    democratic_csi_iscsi_extentRpm: "5400"
    democratic_csi_nfs_zfs_datasetParentName: "pool/k8s/nfs/vols"
    democratic_csi_nfs_zfs_detachedSnapshotsDatasetParentName: "pool/k8s/nfs/snaps"
    democratic_csi_nfs_host: "192.168.1.99"
    democratic_csi_nfs_sc_defaultClass: true
    democratic_csi_nfs_shareAllowedNetworks:
      - "192.168.1.0/24"
      - "192.168.2.0/24"
  roles:
    - role: "infra_monkey.democratic_csi"
