---
- name: Converge
  hosts: all
  connection: local
  become: true
  vars:
    democratic_csi_api_host: "truenas.example.com"
    democratic_csi_api_allowInsecure: true
    democratic_csi_api_key: "astronguniquesecurekey"
    democratic_csi_ssh_host: "truenas.example.com"
    democratic_csi_zfs_sudoEnabled: true
    democratic_csi_zfs_datasetParentName: "pool/k8s/v"
    democratic_csi_zfs_detachedSnapshotsDatasetParentName: "pool/k8s/s"
    democratic_csi:
      keep_tmpfiles: true
      check_config_only: true
      release:
        - name: "truenas-iscsi"
          driver: "freenas-iscsi"
          portal: "192.168.1.99:3260"
          portals:
            - "192.168.1.97:3260"
            - "192.168.1.98:3260"
            - "192.168.1.99:3260"
          portalGroup: "1"
          initiatorGroup: "1"
          zvolBlockSize: "64k"
          extentRpm: "5400"
          ssh_privatekey: |
            -----BEGIN RSA PRIVATE KEY-----
            xxx
            -----END RSA PRIVATE KEY-----
        - name: "truenas-nfs"
          driver: "freenas-nfs"
          sc_defaultClass: true
          zfs_datasetParentName: "pool/k8s/nfs/v"
          zfs_detachedSnapshotsDatasetParentName: "pool/k8s/nfs/s"
          nfs_host: "192.168.1.99"
          nfs_shareAllowedNetworks:
            - "192.168.1.0/24"
            - "192.168.2.0/24"
          ssh_privatekey: |
            -----BEGIN RSA PRIVATE KEY-----
            xxx
            -----END RSA PRIVATE KEY-----
        - name: "truenas-smb"
          driver: "freenas-smb"
          zfs_datasetParentName: "pool/k8s/smb/v"
          zfs_detachedSnapshotsDatasetParentName: "pool/k8s/smb/s"
          smb_host: "192.168.1.99"
          ssh_privatekey: |
            -----BEGIN RSA PRIVATE KEY-----
            xxx
            -----END RSA PRIVATE KEY-----
  roles:
    - role: "infra_monkey.democratic_csi"
